### ISSUE TITLE
Symfony3 Compatibility ?

### ISSUE THREAD

**Issue by ychoucha** [ninsuo/symfony-collection#47] opened 2016-11-17 19:17 UTC
Hello, i m trying to make the script working with symfony 3, but i think now, is not compatible with symfony3

**Comment by ychoucha** [comment] 2016-11-17 19:28
ok so i have tried it but i have the error : 

jquery.collection.js: given collection selector does not exist.


this my Type : 
```

...
	->add('contacts', CollectionType::class, array(
					'entry_type'   => contactType::class,
					'allow_add'    => true,
					'allow_delete' => true,
					'prototype' => true,
					'attr' => array(
							'class' => 'my-selectorContact',
					),
...

```

and this my twig : 


```
    <div class="well">
    
    	{% form_theme form 'bootstrap_3_layout.html.twig' %}
    	{{ form(form) }}
    
    
    </div>

{% endblock %}

{% block js_content %}
    <script
    	src="{{ asset('/vendors/jquery.collection/jquery.collection.js') }}"></script>
    
    <script type="text/javascript">
    	$('.my-selectorinfoPremium').collection();
    </script>
{% endblock %}
```


what is wrong please

**Comment by ninsuo** [comment] 2016-11-18 06:26
Hello, 

Your PHP:
```php
                    'attr' => array(
                            'class' => 'my-selectorContact',
                    ),
```

Your JS:
```js
$('.my-selectorinfoPremium').collection();
```

You should use the same selector for each piece of code

Enjoy,

**Comment by ychoucha** [comment] 2016-11-18 18:05
Hello,
thanks, but still problem :


my formType : 


`      $builder
        	->add('nom',     TextType::class)
        	->add('prenom',     TextType::class)
        ->add('infoPremiumContact', CollectionType::class,
        		array(
        				'entry_type'   => infoPremiumContactType::class,
        				'entry_options' => array(
        						'label' => 'Value',
        				),
        				'allow_add' => true,
        				'allow_delete' => true,
        				'prototype' => true,
        				'required' => false,
        				'attr' => array(
        						'class' => 'my-selectorIPC',
        				)))`

and the second formType : 
`        		array(
        				'entry_type'   => contactType::class,
        				'entry_options' => array(
        						'label' => 'Value',
        				),
        				'allow_add' => true,
        				'allow_delete' => true,
        				'prototype' => true,
        				'required' => false,
        				'attr' => array(
        						'class' => 'my-selector',
        				),`

and on my twig : 

`    <div class="well">
    
    	{% form_theme form 'bootstrap_3_layout.html.twig' %}
    	{{ form(form) }}

    
    </div>

{% endblock %}

{% block js_content %}
    <script
    	src="{{ asset('/vendors/jquery.collection/jquery.collection.js') }}"></script>
    
    <script type="text/javascript">
    	$('.my-selector').collection();
    	$('.my-selectorIPC').collection();
    </script>
{% endblock %}`


and i have this error : 


`
jquery.collection.js: the prefix used in descendant field names is mandatory, you can set it using 2 ways:
jquery....tion.js (ligne 515)
jquery.collection.js: - use the form theme given with this plugin source
jquery....tion.js (ligne 516)

jquery.collection.js: - set name_prefix option to  '{{ formView.myCollectionField.vars.full_name }}'

jquery....tion.js (ligne 517)
jquery.collection.js: given collection selector does not exist.`

what do u think please ?

**Comment by ninsuo** [comment] 2016-11-18 19:25
You should also import the jquery.collection.twig form theme:

```jinja
{% form_theme form 'bootstrap_3_layout.html.twig' 'AppBundle::jquery.collection.twig' %}
{{ form(form) }}
```

**Comment by ychoucha** [comment] 2016-11-19 08:46
Hello,
sorry but i m still not understand how that's works 
where get this files ?

AppBundle::jquery.collection.twig
what i need to add on it ?

**Comment by ninsuo** [comment] 2016-11-19 09:10
Hello,

jquery.collection.twig is given at the root of this repository, along with jquery.collection.js

You can have all the instructions on the demo website:
http://symfony-collection.fuz.org

Have a look to the basic usage:
http://symfony-collection.fuz.org/basic

And the associated controller:
https://github.com/ninsuo/symfony-collection-demo/blob/master/src/Fuz/AppBundle/Controller/BasicController.php

And the associated view:
https://github.com/ninsuo/symfony-collection-demo/blob/master/src/Fuz/AppBundle/Resources/views/Basic/basic.html.twig

**Comment by ninsuo** [comment] 2016-11-19 09:12
You can also read the "Basic usage" part of the README:
https://github.com/ninsuo/symfony-collection/blob/master/README.md

**Comment by phpetra** [comment] 2016-11-20 19:00
I ran into the same problem with Symfony 3 and I think it's an issue due to a change in Symfony's CollectionType field: for some reason it does not render the "attr" option anymore in the html of the collection type. The containing div simply does not get the class of the selector.

I was able to work around this problem by not declaring the "attr" at all but using the "render without twig template" [as described here](http://symfony-collection.fuz.org/options/withoutFormTheme)

In your case it would be something like this, I guess:
```
        $('.my-selectorIPC').collection({
            prototype_name: '{{ form.infoPremiumContact.vars.prototype.vars.name }}',
            allow_add: true,
            allow_remove: true,
            name_prefix: 'form[infoPremiumContact]',
            'add': '<a href="#" class="btn-sm btn-default">Add</a>',
            'add_at_the_end': true
        });```

**Comment by ninsuo** [comment] 2016-11-20 20:22
Thanks for the details.
I'll upgrade Symfony on the demo website then

**Comment by ninsuo** [comment] 2016-11-20 21:06
Hi again,

I migrated most of the project to symfony3 at:
https://github.com/ninsuo/symfony-collection-demo/tree/symfony3.x

I only handled the homepage for now, but do not encounter issues with `attr`.
You can clone and try it anywyay.

Will continue tomorrow to upgrade the whole website to check all options again.

Sorry but I need a reproductible case to help you, do not hesitate to clone the demo and update it with a sample that doesn't work.

**Comment by phpetra** [comment] 2016-11-21 13:57
@ninsuo Thanks for that. I just tried again using the plain symfony bootstrap 3 layout template and indeed it's working fine now.
Before I was using the twig templates of the mopabootstrapBundle and it wasn't rendering the class on the outer div.

**Comment by ninsuo** [comment] 2016-11-25 14:09
I finished to migrate demo website to symfony3
http://symfony-collection.fuz.org/symfony3/

Closing this ticket as no compatibility issue has been found.

If you think there is still a problem, please fork the demo website and reproduce it inside.

Thanks,
A

**Closed by ninsuo** 2016-11-25 14:09 UTC
